default_settings: null
behaviors:
  CaptureTheFlag:
    trainer_type: poca
    hyperparameters:
      batch_size: 512                 # Dramatically reduced from 2048
      buffer_size: 4096               # Maintained 8:1 ratio but much smaller
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2                    # Reduced from 3 to lighten processing load
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128               # Reduced from 256 to lighten network
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 64               # Reduced memory size
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 64            # Reduced from 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    max_steps: 8000000                # Increased to compensate for smaller batches
    time_horizon: 64                  # Reduced from 128
    threaded: true
engine_settings:
  time_scale: 5                       # Dramatically reduced from 10
