behaviors:
  CaptureTheFlag:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    threaded: true

environment_parameters:
  max_episode_steps:
    curriculum:
      - name: First
        completion_criteria:
          measure: progress
          behavior: CaptureTheFlag
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.1
        value: 5000
      - name: Second
        completion_criteria:
          measure: progress
          behavior: CaptureTheFlag
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.3
        value: 7500
      - name: Third
        completion_criteria:
          measure: progress
          behavior: CaptureTheFlag
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.5
        value: 10000